---
title: "ex in HUJI 4"
output: html_document
---

```{r}
library(MASS)

#---A---

neuton_raphson <- function(a,l,w,n){
  diga <- n*log(l) - n*digamma(a)+ sum(log(w))
  ls <- (n*a)/l - sum(w) 
  dda <- n*trigamma(a)
  ddl <- -(n*a)/(l^2)
  dadl <- n/l
  j <- c(diga,ls)
  h <- matrix(c(dda,dadl,dadl,ddl),nrow = 2,ncol = 2)
  n_r <- c(a,l) - ((solve(h)) %*% j)
}

gamma_data <- read.csv("gamma.csv")


#---B---
w <- gamma_data$X15.9916090181
a <- 6.03^2/ 12.29
l <- 6.03/12.29
g <- neuton_raphson(a,l,w,500)
round(g,2)


#---C---
a1 <- (mean(w)^2) / var(w)
l1 <- mean(w) / var(w)
g1 <- neuton_raphson(a1,l1,w,500)
round(g1,2)
```


## 3

```{r}

#---A---
names <- c('id_number', 'diagnosis', 'radius_mean', 
           'texture_mean', 'perimeter_mean', 'area_mean', 
           'smoothness_mean', 'compactness_mean', 
           'concavity_mean','concave_points_mean', 
           'symmetry_mean', 'fractal_dimension_mean',
           'radius_se', 'texture_se', 'perimeter_se', 
           'area_se', 'smoothness_se', 'compactness_se', 
           'concavity_se', 'concave_points_se', 
           'symmetry_se', 'fractal_dimension_se', 
           'radius_worst', 'texture_worst', 
           'perimeter_worst', 'area_worst', 
           'smoothness_worst', 'compactness_worst', 
           'concavity_worst', 'concave_points_worst', 
           'symmetry_worst', 'fractal_dimension_worst')

UCI_data_URL <- read.table(file = "wdbc.data",sep = ',',col.names = names) 
breast_cancer <- UCI_data_URL
breast_cancer$diagnosis = ifelse(breast_cancer$diagnosis == "M",1,0) 


breast_cancer <- breast_cancer[c("diagnosis","perimeter_mean","texture_mean","area_mean")]

model <- glm(diagnosis ~ perimeter_mean+texture_mean+area_mean,data = breast_cancer, family = binomial(link = "logit"))

s_m <- summary(model)
aic_m <- AIC(model)
bic_m <- BIC(model)
model_d <- data.frame(aic_m,bic_m)

mult =  function(xmat0) {
  n = length(xmat0[,1])
  d0 = ncol(xmat0)
  d1 = d0 + 1
  xmat = scale(xmat0)
  cormat = cor(xmat)
  print('Correlation Matrix')
  print(round(cormat,digits=2))
  cor.inv = solve(cormat)
  VIF = rep(0,d0)
  Rj2 = rep(0,d0)
  for (j in 1:d0) {
    VIF[j] = cor.inv[j,j] 
    Rj2[j] = 1 - 1/cor.inv[j,j]
  }
  print('VIF values')
  print(VIF)
  print('Rj2 Values')
  print(Rj2)
  wuns = rep(1,n)
  xmat = cbind(wuns,xmat)
  xtx = t(xmat) %*% xmat
  eig = eigen(xtx)
  eig$values
  sqeig = sqrt(eig$values)
  cond.idx = max(sqeig)/sqeig
  print('Condition Indices and Eigenvectors')
  print(cond.idx)
  print(round(eig$vectors,digits=4))
  pi = matrix(0,d1,d1)
  for (j in 1:d1) {
    for (r in 1:d1) {
      pi[r,j] = eig$vectors[j,r]^2 / eig$values[r]
    }
    pi[,j] = pi[,j] / sum(pi[,j])
  }
  print('Proportion of Variance Table')
  print(round(pi,digits=2))
}
mult(breast_cancer)

new_breast_cancer <- breast_cancer[c("diagnosis","perimeter_mean","texture_mean")]
new_model <- glm(diagnosis ~ perimeter_mean+texture_mean,data = breast_cancer, family = binomial(link = "logit"))
s_m <- summary(new_model)
n_aic <- AIC(new_model)
n_bic <- BIC(new_model)
n_model_d <- data.frame(n_aic,n_bic)
mult(new_breast_cancer)

#---B---
r1 <- resid(new_model)
hist(r1, breaks="Scott", freq=F, xlab = "residuals", col = "darkorchid3", main = "Residuals in the new model")
qqnorm(r1)
qqline(r1,col="red")

r3 = stdres(new_model)
pred = new_model$fitted.values
plot(pred,r3,ylab = "standardized residuals", xlab = "prediction", main = "Residuals analysis", col = "cyan4")


#---C---
i <- UCI_data_URL[which(UCI_data_URL$id_number == "854039"),]
i <- i[c("diagnosis","perimeter_mean","texture_mean","area_mean")]

beta = data.frame(dfbeta(new_model))
betas = data.frame(dfbetas(new_model))
beta$mean <- abs(beta$perimeter_mean+beta$texture_mean)/2
betas$mean <- abs(betas$perimeter_mean+betas$texture_mean)/2
beta[456,c(2,3)]
betas[456,c(2,3)]
```

```{r}
# LOGISTIC REGRESSION

# READ THE DATA
setwd("C:/Users/owner/Desktop")
indat = read.csv("mrfit.csv",header=T,sep=",")
attach(indat)
# These are data on a sample of 5305 men from a follow-up study on risk factors for heart disease.
# The explanatory variables are as follows:
#   age = age in years
#   diab = 0/1 indicator for presence (1) or absence (0) of diabetes
#   chol = cholesterol level
#   map = mean arterial blood pressure [= (2/3)*(diastolic BP) + (1/3)*(systolic BP)
#   smoke = 0/1 indicator for whether the person smokes (1) or does not smoke (0)
# The outcome variable died10 is a 0/1 of whether the person died during the first 10 years of follow-up (died10=1)
#    or survived the entire 10 years (died10=0)

#RUN LOGISTIC REGRESSION AND PRINT OUT BASIC RESULTS
lr1 = glm(died10 ~ age + map, family=binomial(link=logit))
summary(lr1)

#EXTRACT ESTIMATED COEFFICIENTS AND COVARIANCE MATRIX
beta.hat = coef(lr1)
Lambda = vcov(lr1)
beta.hat
Lambda

#CHECK Z STATISTICS
z = beta.hat/sqrt(diag(Lambda))
z

#CONFIDENCE INTERVAL FOR beta.2
za = qnorm(0.975)
beta.hat.2 = beta.hat[3]
cihw = za * sqrt(Lambda[3,3])
beta.2.lo = beta.hat.2 - cihw
beta.2.hi = beta.hat.2 + cihw
za
beta.hat.2
cihw
beta.2.lo
beta.2.hi

#EXPIT FUNCTION
expit = function(u) {
  ans = exp(u)/(1+exp(u))
  return(ans)
}  

#CONFIDENCE INTERVAL FOR P(Y=1|X=x.new)
x.new = c(50,100)
x.new1 = c(1,x.new)
psi.hat = sum(beta.hat*x.new1)
var.psi.hat = t(x.new1) %*% Lambda %*% x.new1
cihw.psi = za * sqrt(var.psi.hat)
psi.lo = psi.hat - cihw.psi
psi.hi = psi.hat + cihw.psi
p.hat = expit(psi.hat)
p.lo = expit(psi.lo)
p.hi = expit(psi.hi)
x.new
psi.hat
var.psi.hat
cihw.psi
psi.lo
psi.hi
p.hat
p.lo
p.hi

#CONFIDENCE INTERVAL FOR ODDS RATIO BETWEEN TWO X CONFIGURATIONS
x1 = c(50,100)
x2 = c(55,90)
x.diff = x2 - x1
beta.hat.sub = beta.hat[2:3]
LL = Lambda[2:3,2:3]
theta.hat = sum(beta.hat.sub*x.diff)
var.th = t(x.diff) %*% LL %*% x.diff
cihw.th = za * sqrt(var.th)
theta.lo = theta.hat - cihw.th
theta.hi = theta.hat + cihw.th
or.est = exp(theta.hat)
or.lo = exp(theta.lo)
or.hi = exp(theta.hi)
x1
x2
x.diff
theta.hat
var.th
cihw.th
theta.lo
theta.hi
or.est
or.lo
or.hi

```

