---
title: "ex in HUJI"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(datasets)


rm(list=ls())

trans_data <- read.csv("transformation.csv", header=T)

x <- trans_data$x
y1 <- trans_data$y1
y2 <- trans_data$y2

plot(x,y1)
plot(x,y2)

plot(x, exp(y1))
plot(x, sqrt(y2))
     
     

rm(list=ls())

data <- mtcars[, -which(names(mtcars) %in% c("am", "vs", "cyl", "gear", "carb"))]
head(data)


summary(data)

plot(x = data$mpg , y = data$wt)
plot(x = data$mpg , y = data$disp)
plot(x = data$mpg , y = data$hp)
plot(x = data$mpg , y = data$drat)
plot(x = data$mpg , y = data$qsec)

cor(data$mpg , data$wt)
cor(data$mpg , data$disp)

Y <- data$mpg
x0 <- rep(1,length(Y))
x1 <-  data$wt
x2 <- data$disp
beta_hat <- inv(t(X)%*%X)%*%t(X)%*%Y
beta_hat

model <- lm(Y ~ X[,2:3], data)
summary(model)
```

```{r}
model <- lm(mpg ~ disp + wt, mtcars )
```
  
```{r}
##number of col of x is the same as y (=model) = 32
X <- cbind(as.matrix(rep(1, 32)), mtcars[, c(3, 6)])
G <- as.matrix(t(x)) %*% as.matrix(X)
expected_e <- as.matrix(resid(model))
ete <- t(expected_e) %*% expected_e
b <- model$coefficients
summary(model)
##freedom degrees = n-p-1 = 29
freedom <- 29
S <- sqrt(ete/freedom)
View(S)
Gr <- rep(0,3)
for(i in 1:ncol(X)) {
Gr[i] <- G[i, i]}
ttest <- (b[2] -0)/(sqrt(Gr) * S)
View(ttest)
```
  
```{r}
critical_t1 <- qt((0.05/2) 29)
critical_t2 <- qt((0.1/2) ,29)
```
  
```{r}
upper_bound_b <- b[2] + (qt(0.95/2, df = 29)) * (((0.05)/2) * s * sqrt(Gr[2]))
lower_bound_b <- b[2] - (qt(0.95/2, df = 29)) * (((0.05)/2) * s * sqrt(Gr[2]))
##cannot say for sure b0 is different then 0 
```
  
```{r}  
upper_bound_sigma <- (29 * (s^2)) / (qchisq(0.05 / 2, df = 29))
lower_bound_sigma <- (29 * (s^2)) / (qchisq(0.95 / 2, df = 29))
##declining H0 assumption
```



```{r}
library("olsrr")
disps <- scale(mtcars$disp)
drats <- scale(mtcars$drat)
wts <- scale(mtcars$wt)
qsecs <- scale(mtcars$qsec)
mpg_model <- lm(mpg ~ disps + drats + wts + qsecs, mtcars)
coll_ans <- ols_coll_diag(mpg_model)
##toleranse: all way above 0 so seems good. qsec and drat are the best in that term.
##condition x seems right, all under 7
```


```{r}
library("MASS")
dat <- Boston
colnames(dat)
dat[,c("rad","chas")] <- list(NULL)
colnames(dat)
```
```{r}
medv_model <- lm(medv ~ crim + zn + indus + nox + rm +  age + dis + tax + ptratio + black + lstat, Boston)
predict <- "medv"
predict_ind <- which(names(dat) == predict)
x_dat <- as.matrix(cbind(rep(1, nrow(dat)),dat[,-predict_ind]), nrows = nrow(estimated, ncols = ncol(estimated)))
G <- solve(t(x_dat) %*% x_dat)
e <- resid(medv_model
n <- nrow(dat)
p <- ncol(dat) -1
s_sqr <- (t(e)%*%e/ (n-p-1))
final_s <- sqrt(s_sqr)
t_vec <- coef(medv_model)/(final_s[1,1]*sqrt(diag(G)))
abs(t_vec)
```

```{r}
p_value <- (1-pt(abs(t_vec), n-p-1))*2
ind <- which(p_value > 0.05/2)
names(dat)[ind]
```

```{r}
hist(e, breaks = "FD")
```

```{r}
P_x <- x_dat %*% G %*% t(x_dat)
I <- diag(nrow(x_dat))
Q <- I-P_x
standard_res <- e / (final_s[1,1]*sqrt(diag(Q)))
b_hat <- coef(medv_model)
estimated_hat <- x_dat %*% b_hat 

plot(standard_res, dat$medv, col = "pink")

medv_model2 <- lm(dat$lstat~ .,dat)
res_lstat <- resid(medv_model2)
plot(standard_res, res_lstat, col = "blue")
```

```{r}
qqnorm(stdres(medv_model))

medv_model3 <- lm(dat$medv ~ dat$lstat)
qqnorm(stdres(medv_model3))
```

```{r}
log_medv <- log(dat$medv)
medv_model4 <- lm(log_medv ~ ., dat[,1:11])
qqnorm(stdres(medv_model4))
```

```{r}
non_ordinary <- (abs(standard_res) >= 3.2)
```


